name: Bug Report
description: File a bug/issue
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Logestic. Your contributions help make Logestic better!

        Use the [Wiki](https://github.com/cybercoder-naj/logestic/wiki) to view the full documentation if your issue is regarding how to use Logestic.

  - type: input
    attributes:
      label: What version of Logestic are you using?

  - type: textarea
    attributes:
      label: What is the bug and how to reproduce it?
      description: Add steps how to re-create this bug and describe it.
      validations:
        required: false 

  - type: textarea
    attributes:
      label: What is the expected behaviour?
      description: A concise description of what you expect to happen.
      validations:
        required: false 

  - type: textarea
    attributes:
      label: Any additional information/media?
      description: Use the same to provide images, code, links, etc.
      validations:
        required: false 
